### ISSUE TITLE
"No json files found in provided path" if templates are in subfolders

### ISSUE THREAD

**Issue by peacemaker360** [sam-cogan/arm-ttk-extension#30] opened 2020-10-08 14:33 UTC
Hi Sam,

I encountered an issue when trying to run tests on templates in subfolders. The error is:
![image](https://user-images.githubusercontent.com/31038013/95470957-ac3c5b80-0981-11eb-9124-306e740ecf87.png)

Example file structure is: 
```bash
.
└── modules
    ├── vnet
    │   ├── vnet.json
    │   └── vnet.parameters.json
    ├── vm
         ├── vm.json
         ├── vm.parameters.json
         └── README.md
```

As of my debugging, I'd suspect that this might be due to difference how PowerShell and PowerShell core are interpreting the Get-Childitem command:

PowerShell:
```powershell
$templatelocation = "..\lib\arm\modules\*"
Get-ChildItem $templatelocation -file -include "*.json", "*.jsonc" -Recurse
# > returns nothing in powershell
Get-ChildItem $templatelocation -include "*.json", "*.jsonc" -Recurse
# > returns files also in subfolders in powershell
```
PowerShell Core:
```powershell
$templatelocation = "..\lib\arm\modules\*"
Get-ChildItem $templatelocation -file -include "*.json", "*.jsonc" -Recurse
# > returns files also in subfolders in pwsh core
Get-ChildItem $templatelocation -include "*.json", "*.jsonc" -Recurse
# > returns files also in subfolders in pwsh core
```

I didn't get if there might be a switch to the ARMTTK Task to run as/in PowerShell core or not, as this might already solve my issue or if the Get-ChildItem could maybe update without the '-file' parameter?

Any ideas? Do you need any further information?

Thanks and best regards,
Fabian

**Comment by sam-cogan** [comment] 2020-10-11 19:59
Thanks for reporting this, it should be resolved now.

**Comment by peacemaker360** [comment] 2020-10-13 13:20
Yes, works now as expected.

**Comment by sam-cogan** [comment] 2020-10-13 19:12
Re-opening, I had to roll back the fix for this as it caused other issues

**Comment by jagratimodi** [comment] 2020-10-14 06:42
Hi @sam-cogan, I am facing the same issue as my templates are present in the sub-folders, I am not able to test the templates using this extension.

![image](https://user-images.githubusercontent.com/22763130/95952605-0fad0a00-0e16-11eb-83a3-1e9e53d1b642.png)

Can you please provide ETA on a fix to this current issue?

**Comment by sam-cogan** [comment] 2020-10-14 07:19
I'll be working on this issue as soon as possible, but as this is being done in my spare time I'm not able to provide an ETA. I appreciate this is preventing you from using the extension and I'll be aiming to resolve it as soon as possible.

**Comment by jagratimodi** [comment] 2020-10-14 10:01
Thanks @sam-cogan  appreciate it! Looking forward to use this extension as soon as this issue resolves.

**Comment by sam-cogan** [comment] 2020-10-14 16:33
I've just pushed an update that should fix this, let me know if not.

**Comment by jagratimodi** [comment] 2020-10-15 06:39
@sam-cogan Yes the issue is now resolved, I am able to test the templates in sub-folders. Thanks a lot for quick fix!

**Closed as completed** 2020-11-03 10:39 UTC
Labels: bug
